apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-managment
  labels:
    app: context-managment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: context-management
      version: v1
  template:
    metadata:
      labels:
        app: context-management
        version: v1
    spec:
      containers:
        - name: context-management
          imagePullPolicy: "Never"
          image: context_management
          ports:
            - containerPort: 1338
---
apiVersion: v1
kind: Service
metadata:
  name: context-management-service
spec:
  ports:
    - port: 1338
      targetPort: 1338
  selector:
    app: context-management
