[project]
name = "holistic_policy"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "hong3nguyen", email = "tringuyennht@gmail.com" }]
dependencies = ["pyyaml>=6.0.2", "pymavlink>=2.4.42"]
readme = "README.md"
requires-python = ">= 3.10"

[tool.rye]
dev-dependencies = []
managed = true
virtual = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.rye.workspace]
members = [
  "src/holistic_policy/*",
  "src/holistic_policy/policy_controlplane/*",
  # "drone",

]
