############################################################
# Example policy to enforce on OPA-Istio sidecars.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  namespace: opa-istio
data:
  policy.rego: |
    package istio.authz

    default allow := false

    # Public endpoint accessible by anyone
    allow if {
      input.parsed_path[0] == "health"
      input.attributes.request.method == "GET"
    }

    # Check if the user has permission
    allow if {
      some user_role in _user_roles[_user_name]
      some permission in _role_permissions[user_role]

      permission.method == input.attributes.request.http.method
      permission.path == input.attributes.request.http.path
    }

    # Extract username from the request's authorization header
    _user_name := parsed if {
      [_, encoded] := split(input.attributes.request.http.headers.authorization, " ")
      [parsed, _] := split(base64url.decode(encoded), ":")
    }

    # Define user roles
    _user_roles := {
      "alice": ["guest"],
      "bob": ["admin"],
      "charlie": ["user"],
    }

    # Define permissions for each role
    _role_permissions := {
      "guest": [
        {"method": "GET", "path": "/preprocessing-gateway"},
        {"method": "GET", "path": "/notify-leader"},
      ],
      "admin": [
        {"method": "GET", "path": "/preprocessing-gateway"},
        {"method": "GET", "path": "/notify-leader"},
        {"method": "GET", "path": "/heartbeat"},
        {"method": "POST", "path": "/update-counter"},
        {"method": "GET", "path": "/get-counter"},
        {"method": "GET", "path": "/get-command"},
      ],
      "user": [
        {"method": "GET", "path": "/preprocessing-gateway"},
        {"method": "GET", "path": "/notify-leader"},
        {"method": "GET", "path": "/heartbeat"},
        {"method": "POST", "path": "/update-counter"},
        {"method": "GET", "path": "/get-counter"},
        {"method": "GET", "path": "/get-command"},
      ]
    }
