# Use the official ROS2 base image
# ubuntu 22.04
#FROM osrf/ros:humble-desktop-full
FROM osrf/ros:humble-desktop

# Install necessary packages
# RUN apt-get update && apt-get install -y jq \
#     git \ 
#     cmake \
#     build-essential \
#     sudo \
#     wget \
#     #ros-iron-desktop \
#     python3-pip\
#     python3-colcon-common-extensions \
#     #vim \
#     && rm -rf /var/lib/apt/lists/*

RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  tcpdump \ 
  vim \
  git \
  cmake \
  build-essential \
  python3-pip \
  python3-venv \
  python3-colcon-common-extensions \
  clang \
  lldb \
  ninja-build \
  libgtest-dev \
  libeigen3-dev \
  libopencv-dev \
  libyaml-dev \
  libgstreamer1.0-dev \
  libgstreamer-plugins-base1.0-dev \
  gstreamer1.0-plugins-good \
  gstreamer1.0-tools \
  sudo \
  wget \
  curl \
  tmux \
  ruby 
# Set up environment
#RUN echo "source /opt/ros/iron/setup.bash" >> /root/.bashrc

WORKDIR /root

# Install PX4
RUN cd /root && \
  git clone -b v1.15.4 --depth 1 https://github.com/PX4/PX4-Autopilot.git --recursive && \
  bash ./PX4-Autopilot/Tools/setup/ubuntu.sh && \
  cd PX4-Autopilot && \
  make px4_sitl

# Setup Micro XRCE-DDS Agent & Client
RUN cd /root && \
  git clone --depth 1 https://github.com/eProsima/Micro-XRCE-DDS-Agent.git && \
  cd Micro-XRCE-DDS-Agent && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make && \
  make install && \
  ldconfig /usr/local/lib/

RUN mkdir -p /root/ws_sensor_combined/src && \
  cd /root/ws_sensor_combined/src && \
  git clone --depth 1 https://github.com/PX4/px4_msgs.git && \
  git clone --depth 1 https://github.com/PX4/px4_ros_com.git && \
  /bin/bash -c "source /opt/ros/humble/setup.bash && cd /root/ws_sensor_combined && colcon build"

# Build ROS 2 Workspace ws_offboard_control
# RUN mkdir -p /root/ws_offboard_control/src && \
#   cd /root/ws_offboard_control/src && \
#   git clone --depth 1 https://github.com/PX4/px4_msgs.git && \
#   git clone --depth 1 https://github.com/PX4/px4_ros_com.git && \
#   /bin/bash -c "source /opt/ros/humble/setup.bash && cd /root/ws_offboard_control && colcon build"

# start the agent

# MicroXRCEAgent udp4 -p 8888
# RUN /bin/bash -c "MicroXRCEAgent udp4 -p 8888 &"

# ros2 run client_drone publisher # gernerate data 
# ros2 run client_drone subscriber # collect data and transform to MAVLink format to 14550 -- notice the protocol udpout://127.0.0.1:14550 
# execute ./px4  # run its own px4 device
# mavlink stop-all
# mavlink start -u 14550 -o 14551 -t 127.0.0.1 -x -f # forwad port 14550 to 14551 (port from GCS)
#
# python3 gcs_setting2.py # listen from port 14551 and print 
# Create and build workspace
RUN mkdir -p /root/drone/src/data

RUN mkdir -p /root/logs

# # Copy the package into the workspace
COPY . /root/drone/src/object_classification

# # Set the working directory
WORKDIR /root/drone/src/object_classification

RUN pip install requests etcd3 pydantic
# Build the workspace
RUN /bin/bash -c "source /root/ws_sensor_combined/install/setup.bash"
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build"


# # Source the setup script
# #RUN echo "source /root/client_drone/src/client_drone/install/setup.bash" >> /root/.bashrc
#
# RUN chmod +x scripts/entrypoint_etcd.sh
# #
# RUN chmod +x scripts/trigger_request.sh
#
# WORKDIR /root/drone/src/object_classification/client_drone
#
# ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
RUN chmod +x scripts/trigger_request.sh

RUN chmod +x scripts/entrypoint_etcd.sh

RUN wget -O /tmp/etcd.tar.gz https://github.com/etcd-io/etcd/releases/download/v3.6.0/etcd-v3.6.0-linux-amd64.tar.gz && \
  tar -xzvf /tmp/etcd.tar.gz -C scripts/ --strip-components=1 && \
  rm /tmp/etcd.tar.gz
# policy
# RUN mkdir policy
#
# WORKDIR /policy
#
# RUN curl -L -o opa https://openpolicyagent.org/downloads/v1.2.0/opa_linux_amd64_static
#
# RUN chmod 755 opa
#
#RUN ./opa run --server --addr=0.0.0.0:8181 --log-level=debug --diagnostic-addr=0.0.0.0:8282 --watch policy.rego 


WORKDIR /root/drone/src/object_classification/client_drone

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

# Define entry point
#CMD ["tmuxinator", "start", "px4_ros2_gazebo_gcs"]
ENTRYPOINT ["/bin/bash", "-c"]

#CMD ["ros2 run client_drone client --ros-args -p yaml_file:=client_drone.yaml"]
