# Use the official ROS2 base image
# ubuntu 24.04
FROM osrf/ros:jazzy

# Install necessary packages
RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  tcpdump \ 
  vim \
  git \
  cmake \
  build-essential \
  python3-pip \
  python3-venv \
  python3-colcon-common-extensions \
  clang \
  lldb \
  ninja-build \
  libgtest-dev \
  libeigen3-dev \
  libopencv-dev \
  libyaml-dev \
  libgstreamer1.0-dev \
  libgstreamer-plugins-base1.0-dev \
  gstreamer1.0-plugins-good \
  gstreamer1.0-tools \
  sudo \
  wget \
  curl \
  tmux \
  ruby 

WORKDIR /root

# Install PX4
RUN cd /root && \
  git clone --depth 1 https://github.com/PX4/PX4-Autopilot.git --recursive && \
  bash ./PX4-Autopilot/Tools/setup/ubuntu.sh && \
  cd PX4-Autopilot && \
  make px4_sitl

# Setup Micro XRCE-DDS Agent & Client
RUN cd /root && \
  git clone --depth 1 https://github.com/eProsima/Micro-XRCE-DDS-Agent.git && \
  cd Micro-XRCE-DDS-Agent && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make && \
  make install && \
  ldconfig /usr/local/lib/

RUN mkdir -p /root/ws_sensor_combined/src && \
  cd /root/ws_sensor_combined/src && \
  git clone --depth 1 https://github.com/PX4/px4_msgs.git && \
  git clone --depth 1 https://github.com/PX4/px4_ros_com.git && \
  /bin/bash -c "source /opt/ros/jazzy/setup.bash && cd /root/ws_sensor_combined && colcon build"


### APLICATION 
# Create and build workspace
RUN mkdir -p /root/drone/src/data

# # Copy the package into the workspace
COPY . /root/drone/src/object_classification

# # Set the working directory
WORKDIR /root/drone/src/object_classification

# RUN pip install requests etcd3 pydantic
# Build the workspace
RUN /bin/bash -c "source /root/ws_sensor_combined/install/setup.bash"
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build"
#
# application_endpoit
RUN chmod +x scripts/trigger_request.sh

WORKDIR /root/drone/src/object_classification/client_drone

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python


# Copy models and worlds from local repository
RUN mkdir -p /root/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/models/
COPY . /root/PX4-ROS2-Gazebo-YOLOv8
COPY models/. /root/.gz/models/
COPY models_docker/. /root/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/models/
COPY worlds/default_docker.sdf /root/PX4-Autopilot/Tools/simulation/gz/worlds/default.sdf


# Additional Configs
RUN echo "source /root/ws_sensor_combined/install/setup.bash" >> /root/.bashrc && \
  echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc && \
  echo "export GZ_SIM_RESOURCE_PATH=/root/.gz/models" >> /root/.bashrc

# setup tmuxinator
RUN echo "export PATH=\$PATH:/root/.local/bin" >> /root/.bashrc

# Copy tmuxinator configuration
COPY tmuxinator_control.yml /root/.config/tmuxinator/tmuxinator_control.yml
# Define entry point
CMD ["tmuxinator", "start", "tmuxinator_control.yml"]

