# check before executing
# minikube profile list
# # or
# minikube status
networks:
  minikube:
    external: true
    name: minikube

services:
  # === Drone 0 Service ===
  client_drone0:
    image: hongtringuyen/ros2_humble_drone:latest
    container_name: client_drone0
    #network_mode: "host"
    networks: [minikube]
    volumes:
      - ./image/:/root/drone/src/data/val_images
      - ../../config/client_config.yaml:/root/drone/src/object_classification/client_drone/client_config.yaml
      - ./logs:/root/drone/logs
    entrypoint: /root/drone/src/object_classification/scripts/entrypoint_etcd.sh
    command: ["drone_0", "drone_0=http://0.0.0.0:2380"]
    stdin_open: true
    tty: true

  # === Drone 1 Service ===
  client_drone1:
    image: hongtringuyen/ros2_humble_drone:latest
    container_name: client_drone1
    networks: [minikube]
    volumes:
      - ./image/:/root/drone/src/data/val_images
      - ../../config/client_config.yaml:/root/drone/src/object_classification/client_drone/client_config.yaml
      - ./logs:/root/drone/logs
    entrypoint: /root/drone/src/object_classification/scripts/entrypoint_etcd.sh
    command: ["drone_1", "drone_1=http://0.0.0.0:2380"]
    stdin_open: true
    tty: true

  # === Drone 2 Service ===
  client_drone2:
    image: hongtringuyen/ros2_humble_drone:latest
    container_name: client_drone2
    networks: [minikube]
    volumes:
      - ./image/:/root/drone/src/data/val_images
      - ../../config/client_config.yaml:/root/drone/src/object_classification/client_drone/client_config.yaml
      - ./logs:/root/drone/logs
    entrypoint: /root/drone/src/object_classification/scripts/entrypoint_etcd.sh
    command: ["drone_2", "drone_2=http://0.0.0.0:2380"]
    stdin_open: true
    tty: true
