FROM debian:stable-slim

WORKDIR /object_classification

# Missing package for opencv
RUN apt-get update
RUN apt-get install -y ffmpeg libsm6 libxext6

COPY ./inference/onnx_model/ ./inference/onnx_model/

COPY --from=ghcr.io/astral-sh/uv:0.4.3 /uv /bin/uv

COPY ./inference/*.toml ./

RUN uv sync --compile-bytecode --no-cache --extra cpu

COPY ./inference/*.py ./inference/

COPY ./inference/*.yaml ./inference/

COPY ./util/ ./util

COPY ./inference/run_server.sh ./inference/run_server.sh

EXPOSE 5012

WORKDIR /object_classification/inference

ENV PATH="/object_classification/.venv/bin:$PATH"

ENTRYPOINT [ "./run_server.sh" ]
