---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efficientnetb0
  labels:
    app: efficientnetb0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efficientnetb0
  template:
    metadata:
      labels:
        app: efficientnetb0
    spec:
      containers:
        - name: efficientnetb0
          imagePullPolicy: "Never"
          image: rdsea/inference:cpu
          ports:
            - containerPort: 5012
          env:
          args: ["--model", "EfficientNetB0"]
---
apiVersion: v1
kind: Service
metadata:
  name: efficientnetb0-service
spec:
  ports:
    - port: 5012
      targetPort: 5012
  selector:
    app: efficientnetb0
