apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  namespace: opa-istio
data:
  policy.rego: |
    package istio.authz

    import input.attributes.request.http as http_request
    import input.parsed_path

    default allow := true
