name: px4_ros2_gazebo
root: /root

windows:
  - Micro_XRCE_Agent:
      root: /root/Micro-XRCE-DDS-Agent
      layout: even-vertical
      panes:
        - MicroXRCEAgent udp4 -p 8888 # add the ip of ROS2 as DDS agent
  - PX4_Autopilot:
      root: /root/PX4-Autopilot
      layout: even-vertical
      panes:
      - sleep 3 && GZ_PARTITION=relay GZ_RELAY=192.168.132.1 GZ_IP=192.168.132.103 PX4_GZ_MODEL_POSE="272.08,-124.22,3.86,0.00,0,-0.7" PX4_GZ_STANDALONE=1 PX4_SYS_AUTOSTART=4001 PX4_SIM_MODEL=gz_x500 /root/PX4-Autopilot/build/px4_sitl_default/bin/px4 -i 2
  - ROS_GZ_Image_Bridge:
      root: /root/ws_sensor_combined
      layout: even-vertical
      panes:
        - sleep 6 && ros2 run ros_gz_image image_bridge /camera
